import http from 'http';
import fs from 'fs';

const server = http.createServer((req, res) => {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.write("<h1 style='color:blue'>Hello World</h1>");
    res.write("Hi, this is a response from the server</br>");
    res.write("<h1>Anubhav Gupta</h1>");
    console.log("Request received");
    res.write("<hr>");
    res.write("<section>");
    res.write("<h2>About this page</h2>");
    res.write("<p>This page is generated by a Node.js http server. It demonstrates sending HTML fragments as the response.</p>");
    res.write("<h3>Quick Links</h3>");
    res.write("<ul>");
    res.write("<li><a href='#'>Home</a></li>");
    res.write("<li><a href='#'>Docs</a></li>");
    res.write("<li><a href='#'>Contact</a></li>");
    res.write("</ul>");
    res.write("<h3>Contact</h3>");
    res.write("<p>Email: <a href='mailto:anubhav@example.com'>anubhav@example.com</a></p>");
    res.write("</section>");
    res.write(`<footer style="margin-top:20px;color:gray;">© ${new Date().getFullYear()} Anubhav Gupta</footer>`);
    res.write("<script>console.log('Client: page loaded');</script>");
    res.end();

    fs.readFile('Cgpa')
});

server.listen(3000, () => {
    console.log("Server is listening on port 3000");
});
